// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uetfwnvzcyxwjfgzaucs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVldGZ3bnZ6Y3l4d2pmZ3phdWNzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEwMTIzNzEsImV4cCI6MjA2NjU4ODM3MX0.hy2I10kDovjCCLnjgffdZTXm26Q771m4awPVnJXIbRE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);